import { PrismaClient } from "@prisma/client";
import "dotenv/config";

const prisma = new PrismaClient();

const SYLLABUS_DATA = [
  {
    title: "Artificial Intelligence & Machine Learning",
    code: "MSCTCC201",
    credit: "4",
    units: {
      "Unit I": [
        "History of AI",
        "Comparison of AI with Data Science",
        "Need and applications of AI",
        "Introduction to Machine Learning",
        "Basics",
        "Reasoning",
        "Problem solving",
        "Knowledge representation",
        "Planning",
        "Learning",
        "Perception",
        "Motion and manipulation",
        "Approaches to AI",
        "Cybernetics and brain simulation",
        "Symbolic",
        "Sub-symbolic",
        "Statistical",
        "Approaches to ML",
        "Supervised learning",
        "Unsupervised learning",
        "Reinforcement learning",
      ],
      "Unit II": [
        "Feature extraction",
        "Statistical features",
        "Principal Component Analysis",
        "Feature selection",
        "Ranking",
        "Decision tree – Entropy reduction and information gain",
        "Exhaustive",
        "Best first",
        "Greedy forward & backward",
        "Applications of feature extraction and selection algorithms",
      ],
      "Unit III": [
        "Classification",
        "Decision tree",
        "Random Forest",
        "Naive Bayes",
        "Support vector machine",
        "Regression",
        "Logistic Regression",
        "Support Vector Regression",
        "Regression trees",
        "Decision tree",
        "random forest",
        "K-Nearest Neighbour (KNN)",
        "Applications of classification and regression algorithms",
      ],
      "Unit IV": [
        "Development of ML Model",
        "Problem identification",
        "Classification",
        "Clustering",
        "Regression",
        "Ranking",
        "Steps in ML modelling",
        "Data Collection",
        "Data pre-processing",
        "Model Selection",
        "Model training (Training, Testing, K-fold Cross Validation)",
        "Model evaluation (understanding and interpretation of confusion matrix, Accuracy, Precision, Recall, True positive, false positive etc.)",
        "Predictions",
        "Hyper parameter Tuning",
      ],
    },
  },
  {
    title: "Data Communication and Computer Networks",
    code: "MSCTCC202",
    credit: "4",
    units: {
      "Unit I": [
        "Data Communications",
        "Components",
        "Direction of Data flow",
        "Networks – Components and Categories",
        "Types of Connections",
        "Topologies",
        "Protocols and Standards",
        "ISO / OSI model",
        "Example Networks",
        "ATM",
        "Frame Relay",
        "ISDN",
        "Physical layer",
        "Transmission modes",
        "Multiplexing",
        "Transmission Media",
        "Switching",
        "Circuit Switched Networks",
        "Datagram Networks",
        "Virtual Circuit Networks",
      ],
      "Unit II": [
        "Data link layer",
        "Introduction",
        "Framing",
        "Error Detection and Correction",
        "Parity",
        "LRC",
        "CRC",
        "Hamming code",
        "Flow and Error Control",
        "Noiseless Channels",
        "Noisy Channels",
        "HDLC",
        "Point to Point Protocols",
        "Medium Access sub layer",
        "ALOHA",
        "CSMA/CD",
        "LAN",
        "Ethernet IEEE 802.3",
        "IEEE 802.5",
        "IEEE 802.11",
        "Random access",
        "Controlled access",
        "Channelization",
      ],
      "Unit III": [
        "Network layer",
        "Logical Addressing",
        "Internetworking",
        "Tunnelling",
        "Address mapping",
        "ICMP",
        "IGMP",
        "Forwarding",
        "Uni-Cast Routing Protocols",
        "Multicast Routing Protocols",
        "Transport Layer",
        "Process to Process Delivery",
        "UDP and TCP protocols",
        "Data Traffic",
        "Congestion",
        "Congestion Control",
        "QoS",
        "Integrated Services",
        "Differentiated Services",
        "QoS in Switched Networks",
        "Application Layer",
        "Domain name space",
        "DNS in internet",
        "Electronic mail",
        "SMTP",
        "FTP",
        "WWW",
        "HTTP",
        "SNMP",
      ],
      "Unit IV": [
        "Introduction to system and network security",
        "Security attacks",
        "Security services and mechanisms",
        "Cryptography",
        "Traditional and Modern Symmetric-Key Ciphers",
        "DES and AES",
        "Asymmetric-Key Cryptography",
        "RSA and ELGAMAL cryptosystems",
        "Message Digest",
        "Digital Signature",
        "Key Management",
        "Network Security",
        "Security at Application Layer (E-MAIL, PGP and S/MIME)",
        "Security at Transport Layer (SSL and TLS)",
        "Security at Network Layer (IPSec)",
        "Firewall and Intrusion Detection",
        "Firewalls and their types",
        "DMZ",
        "Limitations of firewalls",
        "Intruders",
        "Intrusion detection (Host based, Networked, Distributed)",
        "IDS",
        "Malicious software and Internet Security",
        "Viruses and related threats",
        "Virus countermeasures",
        "Denial of service attacks",
        "Hacking",
        "Security policies and plan",
        "Strategies for a secure network",
      ],
    },
  },
  {
    title: "Advanced Operating System",
    code: "MSCTCC203",
    credit: "4",
    units: {
      "Unit I": [
        "Generations",
        "Types",
        "Structure",
        "functions",
        "Services",
        "System Calls",
        "System Boot",
        "System Programs",
        "Protection and Security",
        "Multiprocessor Operating Systems",
        "System Architectures",
        "Structure of OS",
        "Process Concepts",
        "Process States",
        "Process Control Block",
        "Scheduling Criteria, Scheduling Algorithms and their Evaluation",
        "Threads",
        "Threading Issues",
        "Process synchronization",
        "Process Scheduling and Allocation",
        "memory management",
      ],
      "Unit II": [
        "Process synchronization",
        "Critical-Section Problem",
        "Peterson's Solution",
        "Synchronization Hardware",
        "Semaphores",
        "Classic Problems of Synchronization",
        "Monitors",
        "Memory management",
        "Main Memory",
        "Swapping",
        "Contiguous Memory Allocation",
        "Paging",
        "Structure of Page Table",
        "Segmentation",
        "Virtual Memory",
        "Demand Paging",
        "Page Replacement Algorithms",
        "Allocation of Frames",
        "Thrashing",
        "Deadlock",
        "Deadlock Characterization",
        "Deadlock Prevention, Detection and Avoidance",
        "Recovery from Deadlock",
      ],
      "Unit III": [
        "Storage management",
        "Mass-Storage Structure",
        "Disk Structure",
        "Disk Attachment",
        "Disk Scheduling",
        "RAID Structure",
        "File Management",
        "File Concept",
        "Access Methods",
        "Directory Structure",
        "File System Structure",
        "Allocation Methods and Free-Space Management",
      ],
      "Unit IV": [
        "Distributed Operating Systems",
        "System Architectures",
        "Design issues",
        "Communication models",
        "Clock synchronization",
        "Mutual exclusion",
        "Distributed Deadlock detection",
        "Distributed scheduling",
        "Distributed shared memory",
        "Distributed File system",
        "Multimedia file systems",
        "File placement",
        "Caching",
        "Database Operating Systems",
        "Requirements of Database OS",
        "Transaction process model",
        "Synchronization primitives",
        "Concurrency control algorithms",
      ],
    },
  },
  {
    title: "Information Security",
    code: "MSCTCC204",
    credit: "4",
    units: {
      "Unit I": [
        "Definition of security",
        "CIA triad",
        "Assessing security",
        "Security terminology",
        "Historical developments",
        "Structure of security",
        "Introduction to Information Security",
        "The Need for Security",
        "Legal, Ethical, and Professional Issues in Information Security",
      ],
      "Unit II": [
        "Risk Management and Special requirements such as Emanation Security/TEMPEST Standards",
        "Planning for Security",
        "Rainbow Series Reports for DOD",
        "FIPS for all Federal Govt",
        "DHS and CNSS guidance",
        "Firewalls & VPNs",
      ],
      "Unit III": [
        "Cryptography",
        "Evolution of cryptography",
        "Applications of cryptography",
        "Terminology",
        "Caesar ciphers",
        "One-time pads",
        "Operation of DES",
        "AES",
        "Public-key cryptosystems",
        "Topics in Information Systems Security",
        "Minimum privilege",
        "Compartmentalization",
        "Dual controls",
        "Security perimeters",
        "Trustworthy software",
        "Proof of design correctness",
        "Single-points-of-failure",
        "Covert channels",
        "Inference",
        "IDS and Access Control",
        "Physical Security including Emanations Security (EMSEC)/TEMPEST/CFR 32",
        "Marking, Handling, labelling and destruction of Sensitive information",
        "Implementing Security",
        "Security and Personnel",
        "InfoSec Maintenance",
      ],
      "Unit IV": [
        "Security models – Requirements and Types",
        "State-machine models",
        "Mandatory/Discretionary controls",
        "Information-flow models",
        "Informal models",
        "Kerberos Authentication",
        "Authentication in centralized systems",
        "Distributed Authentication",
        "Denial of Service attacks",
        "Security vs. ATM, IP, wireless mobile networks",
        "QoS",
        "Traffic modelling",
        "Security Protocols",
        "Zero-knowledge proofs",
        "Subliminal channels",
        "Oblivious transfer",
        "Digital signature schemes",
        "Bit commitment",
        "Digital cash",
        "Secure contract signing",
        "Secure voting",
        "Digital certified mail",
        "Anonymous message broadcast",
      ],
    },
  },
  {
    title: "Theory of Computation",
    code: "MSCTCC205",
    credit: "2",
    units: {
      "Unit I": [
        "Introduction to theory of computation",
        "Basic Mathematical objects",
        "Sets",
        "Logic",
        "Function",
        "Relation",
        "Languages",
        "Regular and Non regular Languages",
        "A Criterion for Regularity",
        "Minimal Finite Automata",
        "The Pumping Lemma for Regular Languages",
        "Decision Problems",
      ],
      "Unit II": [
        "Regular Language and Finite automata",
        "Regular Languages and Regular expressions",
        "Finite automata and Memory required to recognize a Language",
        "Distinguishing one string from another",
        "Union, Intersections and Complements",
        "Non deterministic Finite Automata",
        "Kleen's theorems",
        "Various conversions like NFA to DFA etc.",
      ],
      "Unit III": [
        "Context Free Grammars and Pushdown Automata",
        "Introduction to grammars",
        "Derivation trees and Ambiguity",
        "An unambiguous CFG for Algebraic Expressions",
        "Simplified Forms and normal Forms",
        "Definitions",
        "Deterministic Push down Automata",
        "PDA corresponding to Given Grammar",
        "CFG corresponding to given PDA",
        "Parsing",
        "Pruning lemma for Context free Languages",
      ],
      "Unit IV": [
        "Turing Machines (TM)",
        "Formal definition and behaviour",
        "Languages of a TM",
        "TM as accepters",
        "Recursive and recursively enumerable languages (REL)",
        "Properties",
        "Universal Turing machine",
        "The Halting problem",
        "Undecidable problems about TMs",
        "Context sensitive language and linear bounded automata (LBA)",
        "Chomsky hierarchy",
        "Decidability",
        "Post's correspondence problem (PCP)",
        "undecidability of PCP",
      ],
    },
  },
  {
    title: "Applied Statistics",
    code: "STAT1IER601",
    credit: "2",
    units: {
      "Unit I": [
        "Introduction to Statistics",
        "Classification of data",
        "On the basis of collection",
        "On the basis of measurement scales",
        "On the basis of its nature",
        "Tabular representation of data – frequency Distributions and contingency tables",
        "Diagrammatic and Graphical Representation of data",
      ],
      "Unit II": [
        "Measures of Central Tendency",
        "Arithmetic Mean",
        "Median",
        "Mode",
        "Geometric Mean and Harmonic Mean",
        "Measures of Dispersion",
        "Range",
        "Mean deviation",
        "Standard Deviation and Quartile deviation",
        "Skewness and Kurtosis",
        "Correlation and Regression",
      ],
      "Unit III": [
        "Sample Surveys",
        "Steps involved in survey sampling",
        "Sampling techniques",
        "Simple random sampling",
        "Stratified sampling",
        "Purposive sampling",
        "Judgement sampling",
        "Quota sampling",
        "Snowball sampling",
      ],
      "Unit IV": [
        "Introduction to Estimation theory – Point and Interval",
        "Testing of Hypothesis",
        "Null and alternative hypothesis",
        "Errors in testing of hypothesis",
        "Level of significance",
        "Power of test",
        "p-value",
        "Parametric tests",
        "single sample t-test",
        "Independent sample t-test",
        "Paired sample t-test",
      ],
    },
  },
];

async function main() {
  console.log("Seeding database with hardcoded syllabus data...");

  for (const courseData of SYLLABUS_DATA) {
    console.log(`Creating Paper: ${courseData.title}`);

    const paper = await prisma.paper.create({
      data: {
        title: courseData.title,
        code: courseData.code,
        credit: courseData.credit,
      },
    });

    for (const [unitTitle, topics] of Object.entries(courseData.units)) {
      const unit = await prisma.unit.create({
        data: {
          title: unitTitle,
          paperId: paper.id,
        },
      });

      let order = 0;
      for (const topicTitle of topics) {
        await prisma.topic.create({
          data: {
            title: topicTitle,
            unitId: unit.id,
            order: order++,
          },
        });
      }
    }

    // Add Custom Unit
    console.log(`Adding Custom Unit to: ${courseData.title}`);
    await prisma.unit.create({
      data: {
        title: "Unit V: Community Topics",
        paperId: paper.id,
        isCustom: true,
      },
    });
  }

  console.log("Seeding completed.");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
